import { Frett } from './frettir';
export const FRETTIR: Frett[] = [
    { id: 1, photo: '../../assets/frettir/car-driving-with-balloons.jpeg' , title: 'Lorem Ipsum is simply dummy text', content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry´s. Lorem Ipsum has been the industry´s standard dummy text since the 1500s, when an', date: '5. Október, 2018', category: 'Íþróttir'},
    { id: 2, photo: '../../assets/frettir/cars.jpeg' , title: 'Lorem Ipsum is simply dummy text', content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry´s. Lorem Ipsum has been the industry´s standard dummy text since the 1500s, when an', date: '5. Október, 2018', category: 'Lífið'},
    { id: 3, photo: '../../assets/frettir/happy-halloween.jpeg' , title: 'Lorem Ipsum is simply dummy text', content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry´s. Lorem Ipsum has been the industry´s standard dummy text since the 1500s, when an', date: '5. Október, 2018', category: 'Tónlist'},
    { id: 4, photo: '../../assets/frettir/man-surfing.jpeg' , title: 'Lorem Ipsum is simply dummy text', content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry´s. Lorem Ipsum has been the industry´s standard dummy text since the 1500s, when an', date: '5. Október, 2018', category: 'Fréttir'},
    { id: 5, photo: '../../assets/frettir/man-with-flag.jpeg' , title: 'Lorem Ipsum is simply dummy text', content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry´s. Lorem Ipsum has been the industry´s standard dummy text since the 1500s, when an', date: '5. Október, 2018', category: 'Fréttir' },
    { id: 6, photo: '../../assets/frettir/man-with-guitar.jpeg' , title: 'Lorem Ipsum is simply dummy text', content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry´s. Lorem Ipsum has been the industry´s standard dummy text since the 1500s, when an', date: '5. Október, 2018', category: 'Tónlist'},
    { id: 7, photo: '../../assets/frettir/man-working.jpeg' , title: 'Lorem Ipsum is simply dummy text', content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry´s. Lorem Ipsum has been the industry´s standard dummy text since the 1500s, when an', date: '5. Október, 2018', category: 'Lífið'},
    { id: 8, photo: '../../assets/frettir/people-with-dog.jpeg' , title: 'Lorem Ipsum is simply dummy text', content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry´s. Lorem Ipsum has been the industry´s standard dummy text since the 1500s, when an', date: '5. Október, 2018', category: 'Lífið'},
    { id: 9, photo: '../../assets/frettir/woman-drinking-coffee.jpeg' , title: 'Lorem Ipsum is simply dummy text', content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry´s. Lorem Ipsum has been the industry´s standard dummy text since the 1500s, when an', date: '5. Október, 2018', category: 'Íþróttir'},
    { id: 10, photo: '../../assets/frettir/camera.jpeg' , title: 'Lorem Ipsum is simply dummy text', content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry´s. Lorem Ipsum has been the industry´s standard dummy text since the 1500s, when an', date: '5. Október, 2018', category: 'Fréttir'},
    { id: 11, photo: '../../assets/frettir/computer.jpeg' , title: 'Lorem Ipsum is simply dummy text', content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry´s. Lorem Ipsum has been the industry´s standard dummy text since the 1500s, when an', date: '5. Október, 2018', category: 'Íþróttir'},
    { id: 12, photo: '../../assets/frettir/couple.jpeg' , title: 'Lorem Ipsum is simply dummy text', content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry´s. Lorem Ipsum has been the industry´s standard dummy text since the 1500s, when an', date: '5. Október, 2018', category: 'Fréttir'},
    { id: 13, photo: '../../assets/frettir/phone.jpeg' , title: 'Lorem Ipsum is simply dummy text', content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry´s. Lorem Ipsum has been the industry´s standard dummy text since the 1500s, when an', date: '5. Október, 2018', category: 'Tónlist'},
    { id: 14, photo: '../../assets/frettir/sitting-on-dock.jpeg' , title: 'Lorem Ipsum is simply dummy text', content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry´s. Lorem Ipsum has been the industry´s standard dummy text since the 1500s, when an', date: '5. Október, 2018', category: 'Lífið'},
    { id: 15, photo: '../../assets/frettir/summer-fun.jpeg' , title: 'Lorem Ipsum is simply dummy text', content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry´s. Lorem Ipsum has been the industry´s standard dummy text since the 1500s, when an', date: '5. Október, 2018', category: 'Íþróttir'},
    { id: 16, photo: '../../assets/frettir/logs.jpg' , title: 'Lorem Ipsum is simply dummy text', content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry´s. Lorem Ipsum has been the industry´s standard dummy text since the 1500s, when an', date: '5. Október, 2018', category: 'Tónlist'}
]
